name: Backend CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3

      - name: Run backend deployment script
        run: ./scripts/deploy-backend.sh
